compile:
	g++ --std=c++20 -L/opt/homebrew/Cellar/boost/1.82.0_1/lib -I/opt/homebrew/Cellar/boost/1.82.0_1/include  -lboost_filesystem-mt -lboost_thread-mt main.cc -o exec
execute:
	./exec
run: compile execute
